### ISSUE TITLE
Where is the data download link?

### ISSUE THREAD

**Issue by DDxk369** [DeepPathology/CanineCutaneousTumors#1]
Hello, I found that the location of the data download link is empty, may I ask where I can download the data used in this work?

**Comment by FraukeWilm** [comment]
Hi, 

thanks for the hint. The data can be downloaded here:  [https://wiki.cancerimagingarchive.net/display/Public/CAnine+CuTaneous+Cancer+Histology+%28CATCH%29+Dataset](https://wiki.cancerimagingarchive.net/display/Public/CAnine+CuTaneous+Cancer+Histology+%28CATCH%29+Dataset). We have added the link to the ReadMe. 

Best,
Frauke
